### ISSUE TITLE
Croppa deletes all files starting with the beginning of the src file name.

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#96] opened 2015-06-19 09:37 UTC
For example. You have Foo.png and Foo-1.png.
You now delete Foo.png. It will also delete its crops (Which is a function deleting any file starting with Foo) So Foo-1.png will also be deleted.

**Comment by weotch** [comment] 2015-06-19 21:58
This is a duplicate of #93, which I just pushed up a fix for.

**Closed by weotch** 2015-06-19 21:58 UTC

**Comment by sdebacker** [comment] 2015-06-26 08:17
What about a new release ? It's a critical bug.

**Comment by weotch** [comment] 2015-06-26 15:17
Sure thing, released here: https://github.com/BKWLD/croppa/releases/tag/4.0.5
