### ISSUE TITLE
Feature request: Make it configurable where croppa saves thumbs

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#66] opened 2015-01-20 08:08 UTC
As the title says, I'd really like to save the thumbs in a different folder then the source image

**Comment by weotch** [comment] 2015-01-20 18:06
Yeah, I like that idea.  I probably won't hop on it, but I'm totally open to a PR for that.

**Comment by Bayasgalan** [comment] 2015-02-02 10:13
yes. me too.

**Comment by weotch** [comment] 2015-02-09 21:13
Realized this was a dupe of #36

**Closed by weotch** 2015-02-09 21:13 UTC
