### ISSUE TITLE
Bug with version 4.3.4 and 3.5.0 on Laravel 4

### ISSUE THREAD

**Issue by sdebacker** [BKWLD/croppa#77] opened 2015-03-02 20:52 UTC
Version 4.3.4 and 3.5.0 are broken, so with Laravel 4.2 you should use v4.3.2.
The package doesn't find the image even if it exists. Probably the stream problem ?

**Comment by weotch** [comment] 2015-03-02 21:35
I'm using 3.5.0 on a L4.2 project right now without issue.  I did recently change some internals regarding finding images in the filesystem.  Can you show me what your src_dirs config is and where the files actually are?

**Comment by weotch** [comment] 2015-03-02 21:36
I wonder if it could be https://github.com/BKWLD/croppa/issues/13 that introduced your issue ...

**Comment by JayBizzle** [comment] 2015-03-02 21:42
I've had to revert back to Coppa 3.4.3 to get my application working again

**Comment by weotch** [comment] 2015-03-02 21:56
Well balls, I had no idea those commits were causing issues. I even added more unit tests to try to harden it.  If you can let me know particulars of how you use Croppa, like what you put for src_dirs and where the files are actually located and stuff like that, I can try to make some tests around your environment to fix.

These are the tests designed to validate filesystem stuff: https://github.com/BKWLD/croppa/blob/master/tests/TestCheckForFile.php

**Comment by JayBizzle** [comment] 2015-03-02 21:58
My setup is really simple...just like this...

```<img  src="{{ Croppa::url('/assets/frontend/imgs/shows/' . $g->show_id . '/' . $g->filename, 300, 200) }}" />```

No extra config specified

**Comment by weotch** [comment] 2015-03-02 22:05
Ahh, I think the problem is that I'm checking now (#13 and 3.5.0) that the referenced image is within the src_dir from the config file.  The default config expects it to be at `public_path()."/uploads"` (https://github.com/BKWLD/croppa/blob/master/src/config/config.php#L7) but yours is at `public_path()."/assets"` and, thus, a 404 is returned.  Try publishing the config file and changing that `src_dirs` config.

**Comment by sdebacker** [comment] 2015-03-02 22:34
In my case the config is default:
```php
'src_dirs' => array(
    App::make('path.public'),
),
``` 
and images are in ```/public/uploads``` folder. I first get a 500 error and have to reload page for the image to show up.

**Comment by sdebacker** [comment] 2015-03-02 22:35
issue https://github.com/BKWLD/croppa/issues/74

**Comment by weotch** [comment] 2015-03-02 23:21
Yeah, @sdebacker that sounds different than @JayBizzle 's issue and does sound related to the Response part of the ServiceProvider.  However, #74 / # 75 fixes an issue that was introduced in 3.6.0 and you're encountering it in 3.5.0.

**Comment by sdebacker** [comment] 2015-03-03 07:02
Yes, that's strange. I have the same problem with 4.3.4

**Comment by zodthepossum** [comment] 2015-03-05 03:10
I've been using Croppa for a year now on a couple of Laravel 4.1 sites and suddenly it just stopped producing the quadrant(c).jpg files when I post new images, and is not working properly - images do not render properly in the views only the name shows up.  I have not changed anything in my app and am just wondering if you know what could be wrong.
Croppa is declared as "bkwld/croppa": "~3.0" in composer.json

**Comment by weotch** [comment] 2015-03-05 16:41
@zodthepossum can you supply your src_dirs config and the actual location of your src files?

**Comment by zodthepossum** [comment] 2015-03-05 21:25
@weotch i guess this is what you need...
Input::file('attachment')->move(public_path() . '/upload/images', $image->path);
					$image->save();
File locations in public/upload/images
let me know if you need more info, it has worked b/4

**Comment by weotch** [comment] 2015-03-05 21:59
So you didn't customize Croppa's [`src_dirs` config var](https://github.com/BKWLD/croppa/blob/master/src/config/config.php#L7) at all then?

**Comment by zodthepossum** [comment] 2015-03-08 22:13
@weotch no i had not done so before, thankyou though it worked!

**Comment by sdebacker** [comment] 2015-03-09 08:28
sorry for the late response. Here is my src_dirs:
```php
'src_dirs' => array(
	App::make('path.public'),
),
```
dirs are /public/uploads/module_name/

**Comment by zodthepossum** [comment] 2015-03-10 00:55
@weotch & @sdebacker 
still having issues, this time only on production after i successfully uploaded my laravel app to a shared server.  the issue now is to get it working i had to move most of the laravel app above public_html (app, bootstrap, vendor & associate files) everything under the public folder is now in /public_html/sputnikart.net (url is sputnikart.net).  i did a die dump on a view {{ dd(public_path()) }} and the path is
"/home/abstract/laravelsput/bootstrap" 
today i find laravel had created /upload/images folders (permissions altered to 777) under public path & even though i get messages saying image upload is successful, quadrant c files are created, the images do not render properly - any ideas?

in in bkwld/croppa/src/config/config.php
'src_dirs' => array(
		App::make('path.public').'/upload/images',
	),
'host' => 'http://sputnikart.net',

'public' => '/home/abstract/laravelsput/bootstrap',

in blades declared this way <img src="{{ Croppa::url('/upload/images/' . $image->path,......

in controller declared this way Input::file('attachment')->move(public_path() . '/upload/images', $image->path);

**Comment by weotch** [comment] 2015-03-10 03:09
Couple questions:

1. Does it work without the quadrant option?  
2. Are files being generated in /upload/images?  Or anywhere that you can find them?
3. If I understand you correctly, it sounds like your app is installed at /public_html/sputnikart.net but Laravel is reading the `public_path` as being /home/abstract/laravelsput/bootstrap ... is that right?  So Laravel has your `public_path` wrong?
4. Have you tried specifying Croppa @ 4.3.2 in your composer file and seeing if that fixes it?

**Comment by zodthepossum** [comment] 2015-03-10 03:31
hi robert

On 10/03/2015 2:10 pm, Robert Reinhard wrote:
>
> Couple questions:
>
>  1. Does it work without the quadrant option?
>
it is generating quadrant files now in 
home/abstract/laravelsput/bootstrap/upload/images
>
>  1. Are files being generated in /upload/images? Or anywhere that you
>     can find them?
>
file structure

home/abstract/laravelsput/...
                         app/
                         bootstrap/
                              upload/images (files are saving to here - 
created by laravel)
                         vendor/
                         public_html/
                                     sputnikart.net/
                                         css/
                                         fonts/
                                         js/
                                         packages/
                                         upload/
                                             images/     (this is where 
locally the files were saving to)

>  1. If I understand you correctly, it sounds like your app is
>     installed at /public_html/sputnikart.net but Laravel is reading
>     the |public_path| as being /home/abstract/laravelsput/bootstrap
>     ... is that right? So Laravel has your |public_path| wrong?
>
i could not get my app working on shared host so i followed these 
instructions
http://stackoverflow.com/questions/16683046/how-to-install-laravel-4-to-a-web-host-subfolder-without-publicly-exposing-app/16683938#comment25831529_16683938

scroll down to the 40 votes section & now it is working - probably has 
something to do with

In the paths.php file, replace:

|'public'  =>  __DIR__.'/../public',|

with:

|'public'  =>  __DIR__,|

>  1. Have you tried specifying Croppa @ 4.3.2 in your composer file and
>     seeing if that fixes it?
>
i'll try that i was a little hesitant because i saw there were some 
issues, i can allways roll it back right?

i'll let you know how i go
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/BKWLD/croppa/issues/77#issuecomment-77988425>.
>

-- 

Susana de Almeida

@bstractal <http://www.abstractal.com.au>

02 67252120

**Comment by zodthepossum** [comment] 2015-03-10 03:39
tried specifying croppa 4.3.2 in composer.json and my app stopped 
working, put it back to 3.0 now ok

On 10/03/2015 2:10 pm, Robert Reinhard wrote:
>
> Couple questions:
>
>  1. Does it work without the quadrant option?
>  2. Are files being generated in /upload/images? Or anywhere that you
>     can find them?
>  3. If I understand you correctly, it sounds like your app is
>     installed at /public_html/sputnikart.net but Laravel is reading
>     the |public_path| as being /home/abstract/laravelsput/bootstrap
>     ... is that right? So Laravel has your |public_path| wrong?
>  4. Have you tried specifying Croppa @ 4.3.2 in your composer file and
>     seeing if that fixes it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/BKWLD/croppa/issues/77#issuecomment-77988425>.
>

-- 

Susana de Almeida

@bstractal <http://www.abstractal.com.au>

02 67252120

**Comment by zodthepossum** [comment] 2015-03-10 23:39
@weotch thank you so much for your help, i managed to get public path working properly and upgraded to 4.3.2 - now all ok! thanks again!

**Comment by urbankid** [comment] 2015-03-28 19:07
I had to revert to version 3.4.3 as well to solve the "reference file not found" issue.
My setup has the public folder in a different location than the default Laravel setup.
In other versions I solve it with:

'src_dirs' => array(
		// App::make('path.public'),
		'../html'
	),

but couldn't solve it in the latest version of Croppa.

**Comment by weotch** [comment] 2015-03-30 16:14
Well, what I'm realizing is that I should have made 3.5 a major point release, I didn't realize my tightening the effect of the `src_dirs` config would break folks use cases.

Next week I'm going to start on a 4.0 release that will change `src_dirs` again to add support for S3 (#52) via replacing all the disk IO stuff with [Flysystem](http://flysystem.thephpleague.com/).  I intend to tackle #36 with this as well, which will give users more control about where images are found.

**Comment by weotch** [comment] 2015-04-13 18:25
Closing this now that [4.0 is released](https://github.com/BKWLD/croppa/releases/tag/4.0.0).  There is a new configuration schema (*breaking change*) that more explicitly expresses how Croppa deals with routes and URLs.

**Closed by weotch** 2015-04-13 18:25 UTC

**Comment by sdebacker** [comment] 2015-04-13 18:29
Very nice new release ! Thanks.
